version: '3.3'

services:
  db:
    restart: always
    image: postgres:9.6.5
    container_name: cargamos_postgres #you can change this
    environment:
      - POSTGRES_USER=cargamos
      - POSTGRES_PASS=cargamos_password
      - POSTGRES_DB=cargamos
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

  web:
    container_name: flask_app
    restart: always
    build:
      context: ""
      dockerfile: compose/Dockerfile
    command: bash -c "export FLASK_CONFIGURATION=production && gunicorn -w 1 -b 0.0.0.0:8000 app:app"
    env_file:
      - .env/.dev
    volumes:
      - static_volume:/home/ubuntu/cargamos/static
      - media_volume:/home/ubuntu/cargamos/media
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  nginx:
    build: compose/nginx
    volumes:
      - static_volume:/home/ubuntu/cargamos/static
      - media_volume:/home/ubuntu/cargamos/media
    ports:
      - 80:80
    #      - 443:443
    expose:
      - 80
    depends_on:
      - web

  celery_worker:
    build:
      context: ""
      dockerfile: compose/Dockerfile
    image: flask_celery_example_celery_worker
    command: /worker_start
    env_file:
      - .env/.dev
    environment:
      - FLASK_CONFIGURATION=production
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: ""
      dockerfile: compose/Dockerfile
    image: flask_celery_example_celery_beat
    command: /beat_start
    env_file:
      - .env/.dev
    environment:
      - FLASK_CONFIGURATION=production
    depends_on:
      - redis
      - db

  flower:
    build:
      context: ""
      dockerfile: compose/Dockerfile
    image: flask_celery_example_celey_flower
    command: /flower_start
    env_file:
      - .env/.dev
    environment:
      - FLASK_CONFIGURATION=production
    ports:
      - 5557:5555
    expose:
      - 5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: